[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "coreax"
dynamic = ["version"]
description = "Jax coreset algorithms."
readme = "README.md"
requires-python = ">=3.9"
keywords = [
    "coreset",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
license = {file = "LICENSE"}
authors = [
    # TODO: Populate author data when ready to publish
    {name = "GCHQ", email = "todo@todo.com"},
]
dependencies = [
    "flax",
    "jax",
    "jaxopt",
    "optax",
    "scikit-learn",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "furo",
    "imageio",
    "matplotlib",
    "myst-parser",
    "numpy",
    "opencv-python",
    "pre-commit",
    "pyqt5",
    "pytest",
    "scipy",
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinxcontrib-bibtex",
]

[project.urls]
Repository = "https://github.com/gchq/coreax"

[tool.isort]
known_first_party = ["coreax", "examples"]
profile = "black"

[tool.setuptools]
packages = ["coreax"]

[tool.setuptools.dynamic]
version = {attr = "coreax.__version__"}

[tool.coverage.run]
branch = true
source = ["coreax"]
command_line = "-m unittest discover -s tests/unit"
omit = ["*/__init__.py", "*/__main__.py", "tests/integration/*"]

[tool.coverage.report]
sort = "Cover"
exclude_lines = [
    "pass",
    "raise RuntimeError"
]
