name: Unit Tests and Coverage Assessment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  tests:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-test.txt ]; then pip install --no-dependencies -r requirements-test.txt; fi
    - name: Test with pytest
      run: |
        pytest --cov=. --cov-branch --cov-report=term-missing --ignore=tests/integration
